### PR TITLE
company tab

### PR DESCRIPTION
**Pull request by joseapcordeiro**
add this to company tab

### CODE REVIEW

**Comment by mehul8236** [comment]
Good job jose! :)

**Comment by kunaldodiya** [comment]
good but i am lost :(

**Comment by kunaldodiya** [comment]
sent me invitation link mak :) have you again created another repo ?

**Comment by mehul8236** [comment]
I am working on Admin panel and url starts from 'admin/*', so please don't write a controller which aceess admin url and beyond! :)

**Pull request merged**
